[package]
name = "polkadot-statement-table"
version = "0.8.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.3.6", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.34" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
